In [2]:
import numpy as np

In [3]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
print(arr1)
arr1[0] = 90 ## SHALLOW COPY
print(arr1, a)

[4 5 6 7 8]
[90  5  6  7  8] [ 1  2  3 90  5  6  7  8  9 10]


In [4]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [5]:
print(np.vstack((a1, a2)))
print("="*100)
print(np.hstack((a1, a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [6]:
x = np.arange(1, 25).reshape(2, 12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [7]:
print(np.hsplit(x, 3))

[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]


In [8]:
X = np.arange(1,25)
print(X)
print(np.hsplit(X,3))
print(np.hsplit(X,(4,6)))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15, 16]), array([17, 18, 19, 20, 21, 22, 23, 24])]
[array([1, 2, 3, 4]), array([5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24])]


In [9]:
a = np.array([
    [1, 2],
    [3,2],
    [4,6]
])
b = a.copy()
b[0] = [4,4]
print(a,b,sep="\n\n")

[[1 2]
 [3 2]
 [4 6]]

[[4 4]
 [3 2]
 [4 6]]


In [10]:
a = np.array([
    [1, 2],
    [3,2],
    [4,6]
])
b = a.copy()
b[0,0] = 0
print(a,b,sep="\n\n")

[[1 2]
 [3 2]
 [4 6]]

[[0 2]
 [3 2]
 [4 6]]


In [12]:
q = np.array([1,2,3])
qq = np.array([[1,2,3],[3,4,5]])
print(q.sum())
print(qq.sum())
print(qq.min())

6
18
1
