In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[1,2]])
print(a+b)

[[2 4]
 [4 6]
 [6 8]]


In [5]:
a = np.random.default_rng()
print(a)
print(a.random(5))

Generator(PCG64)
[0.64187368 0.74196485 0.21736978 0.25831379 0.9493839 ]


GENERATE RANDOM NUMBERS

In [7]:
genrator = np.random.default_rng()
print(genrator.integers(5, size=(2,4), endpoint=True))

[[5 5 2 4]
 [0 5 2 3]]


In [10]:
##UNIQUE ITEMS
a = np.array([1,2,3,4,4,3,5,6,6,5,4,5,6,7,8,3,6,5,3,34])
print(np.unique(a))
print(np.unique(a,return_counts=True))
print(np.unique(a, return_index=True))
# print(np.unique(a, return_counts=True, return_index=True))


[ 1  2  3  4  5  6  7  8 34]
(array([ 1,  2,  3,  4,  5,  6,  7,  8, 34]), array([1, 1, 4, 3, 4, 4, 1, 1, 1], dtype=int64))
(array([ 1,  2,  3,  4,  5,  6,  7,  8, 34]), array([ 0,  1,  2,  3,  6,  7, 13, 14, 19], dtype=int64))


In [17]:
_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 91]])


In [18]:
unique_values = np.unique(_2d)
print(unique_values) ##IF NO AXIS IS GIVEN THE 2 D ARRAY IS FLATTENED
print(np.unique(_2d, axis=0))
print(np.unique(_2d, axis=1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 91]
[[ 1  2  3  4]
 [ 1  2  3 91]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3 91]]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.flip(arr))

[8 7 6 5 4 3 2 1]


In [21]:
arr = np.array([
    [1,2,3],
    [4,3,2],
    [5,7,5]
])
print(np.flip(arr))
print(np.flip(arr,axis=0))
print(np.flip(arr,axis=1))

[[5 7 5]
 [2 3 4]
 [3 2 1]]
[[5 7 5]
 [4 3 2]
 [1 2 3]]
[[3 2 1]
 [2 3 4]
 [5 7 5]]


In [26]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
X = x.flatten()
X[0] = 6969
print(x)
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[6969    2    3    4    5    6    7    8    9   10   11   12]


In [27]:
X = x.ravel()
X[0] = 6969
print(x)
print(X)

[[6969    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
[6969    2    3    4    5    6    7    8    9   10   11   12]
