In [1]:
import numpy as np

In [2]:
listarray = np.array([[1,2,3], [5,8,5],[0,3,1]])

In [3]:
print(listarray)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [5]:
print(listarray.dtype)

int32


In [6]:
print(listarray.shape)

(3, 3)


In [7]:
print(listarray.size)

9


In [8]:
a = np.array({1,2,3,4})
print(a, a.dtype, a.shape, sep="\n")

{1, 2, 3, 4}
object
()


In [13]:
zeros = np.zeros((5))
print(zeros)

[0. 0. 0. 0. 0.]


In [14]:
zeros = np.zeros((1,5))
print(zeros)

[[0. 0. 0. 0. 0.]]


In [15]:
zeros = np.zeros((2,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
zeros = np.zeros((5,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [40]:
qq = np.full((3,4), 69)
print(qq)

[[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]]


In [18]:
q = np.arange(2,10)
print(q)

[2 3 4 5 6 7 8 9]


In [20]:
## Generates 10 numbers between 1 and 20 with equal spacing.
lspace = np.linspace(1,20,10)
print(lspace)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [22]:
empty = np.empty((4,6))
print(empty)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.11261434e-306
  1.33511018e-306 1.42413555e-306]
 [1.78019082e-306 1.37959740e-306 6.23057349e-307 1.02360935e-306
  1.69120416e-306 1.78022342e-306]
 [6.23058028e-307 1.06811422e-306 9.45699680e-308 1.11258854e-306
  1.11261502e-306 1.42410839e-306]
 [7.56597770e-307 6.23059726e-307 1.42419530e-306 9.79101761e-307
  9.34601642e-307 1.60219035e-306]]


In [26]:
empty2 = np.empty(2)
print(empty2)

[1.22824072e-025 1.74884964e+254]


In [27]:
empty3 = np.empty((1,2))
print(empty3)

[[1.22824072e-025 1.74884964e+254]]


In [39]:
a = np.arange(100)
empty_like2 = np.empty_like(a)
print(empty_like2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [42]:
ide = np.identity(4)
print(ide)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
cd = np.arange(12)
print(cd, cd.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [45]:
q = cd.reshape(3,4)
qq = cd.reshape(4,3)
qqq = cd.reshape(2,6)
print(q,qq,qqq,sep="\n\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [47]:
print(qq)
print(qq.reshape(1,12))
print(qq.ravel())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
