In [1]:
import numpy as np

In [2]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,1,0]
])
print(x)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [3]:
print(x.sum(axis=0))
print(x.sum(axis=1))

[12  8  9]
[ 6 15  8]


In [4]:
print(x.T)

[[1 4 7]
 [2 5 1]
 [3 6 0]]


In [5]:
print(x.flat)

In [6]:
for item in x.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [7]:
print(x.ndim)

2


In [8]:
print(x.size)

9


In [9]:
print(x.nbytes, x.dtype)

36 int32


In [10]:
one = np.array([1,2,3])

In [11]:
print(one.argmax())
print(x.argmax())

2
6


In [12]:
print(x.argmax(axis=0))

[2 1 1]


In [13]:
print(x.argmax(axis=1))

[2 2 0]


In [14]:
print(one.argsort())

[0 1 2]


In [19]:
print(x)
print(x.argsort(axis=0))
print(x.argsort(axis=1))

[[1 2 3]
 [4 5 6]
 [7 1 0]]
[[0 2 2]
 [1 0 0]
 [2 1 1]]
[[0 1 2]
 [0 1 2]
 [2 1 0]]
