In [1]:
import numpy as np

In [6]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,1,0]
])

b = np.array([
    [1,2,1],
    [4,0,6],
    [8,1,0],
    # [1,1,1] will give error
])

In [7]:
print(a+b)

[[ 2  4  4]
 [ 8  5 12]
 [15  2  0]]


In [8]:
print(a*b)

[[ 1  4  3]
 [16  0 36]
 [56  1  0]]


In [9]:
print(a-b)

[[ 0  0  2]
 [ 0  5  0]
 [-1  0  0]]


In [12]:
print(a**b)

[[      1       4       3]
 [    256       1   46656]
 [5764801       1       1]]


In [13]:
print(a,np.sqrt(a),np.square(a),sep="\n")

[[1 2 3]
 [4 5 6]
 [7 1 0]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 1.         0.        ]]
[[ 1  4  9]
 [16 25 36]
 [49  1  0]]


In [17]:
print(a)
print(np.where(a>0))
print(type(np.where(a>0)))

[[1 2 3]
 [4 5 6]
 [7 1 0]]
(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))
<class 'tuple'>


In [22]:
print(np.count_nonzero(a))
print(np.nonzero(a))
print(np.zeros_like(a))

8
(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
import sys
aa = np.array([0,4,55,2], dtype=int)
print(sys.getsizeof(1)*len(aa))

112


In [26]:
print(aa.itemsize * a.size)

36
